Use null coalesce to avoid null warning.
SwedbankPay/swedbank-pay-sdk-php pull request #101
Opened 2022-09-23 12:14 UTC by letharion

Passing null in place of a string yields a deprecated warning in PHP 8, so we use ?? '' to get an empty string in place a null value.

2022-09-23 12:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SwedbankPay/swedbank-pay-sdk-php?pullRequest=101) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SwedbankPay/swedbank-pay-sdk-php?pullRequest=101) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SwedbankPay/swedbank-pay-sdk-php?pullRequest=101) it.</sub>

2022-10-04 08:50 UTC, asbjornu commented
@letharion thank you for this PR. Can you please sign our [CLA](https://cla-assistant.io/SwedbankPay/swedbank-pay-sdk-php?pullRequest=101)?

2022-10-08 06:15 UTC, olegisk commented
@letharion Sorry, but i think this solution is quite rough.
There will be ran follow code that checks that class "" is exists. Like:
```php
if (class_exists('')) {
	echo 'true';
} else {
	echo 'false';
}
```

I think it should be like:
```php
        if ($this->getRequestService()->getResponseResourceFQCN() &&
            class_exists($this->getRequestService()->getResponseResourceFQCN())
        ) {
            $responseResourceFCQN = $this->getRequestService()->getResponseResourceFQCN();
            $responseResource = $this->resourceFactory->createFromFqcn($serviceBaseName, $responseResourceFCQN, $data);
            $this->setResponseResource($responseResource);
            return;
        }
```

2022-10-08 06:23 UTC, olegisk requested changes

2022-10-08 06:23 UTC, olegisk commented on src/SwedbankPay/Api/Service/Response.php
> +        if (class_exists($this->getRequestService()->getResponseResourceFQCN() ?? '')) {
It checks class like `if (class_exists('')) {`
I guess it's quite rude

2022-10-11 17:08 UTC, closed without merging