Implemented MobilePay
SwedbankPay/swedbank-pay-sdk-php pull request #15
Opened 2020-02-18 06:47 UTC by aait

2020-02-18 13:26 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:29 UTC, asbjornu commented on tests/MobilePayPaymentTest.php
> +        $mobilePayPaymentObject->setShoplogoUrl('https://test-dummy.net/logo.png');
Why set `shopLogoUrl` to an URL that doesn't exist?

2020-02-18 13:30 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateAuthorization.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/authorizations');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:30 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/cancellations');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:30 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/captures');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:30 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/reversals');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:30 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/authorizations/%s');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:31 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/authorizations');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:31 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/cancellations/%s');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:31 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/cancellations');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:31 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/captures/%s');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:31 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/captures');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:31 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/reversals/%s');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:31 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/reversals');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:32 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/transactions/%s');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:32 UTC, asbjornu commented on src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php
> +        $this->setRequestEndpoint('/psp/mobilepay/payments/%s/transactions');
[Please don't build or parse URLs](https://developer.swedbankpay.com/#uri-usage).

2020-02-18 13:33 UTC, asbjornu commented on tests/MobilePayPaymentTest.php
> +        $url->setCompleteUrl('https://test-dummy.net/payment-completed')
Why sett all these URLs to something that doesn't exist?

2020-02-27 12:06 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SwedbankPay/swedbank-pay-sdk-php?pullRequest=15) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SwedbankPay/swedbank-pay-sdk-php?pullRequest=15) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SwedbankPay/swedbank-pay-sdk-php?pullRequest=15) it.</sub>

2020-03-12 09:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SwedbankPay/swedbank-pay-sdk-php?pullRequest=15) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SwedbankPay/swedbank-pay-sdk-php?pullRequest=15) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SwedbankPay/swedbank-pay-sdk-php?pullRequest=15) it.</sub>

2020-04-06 11:25 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +        $mobilePayPaymentObject = new MobilePayPaymentObject();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid excessively long variable names like $mobilePayPaymentObject. Keep variable name length under 20.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-04-06 11:25 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/MobilePayPaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- tests/MobilePayPaymentTest.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-04-07 00:35 UTC, asbjornu commented
@aait, @olegisk, please pick this up alongside the refactoring to not parse or build URLs.

2020-05-14 08:57 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/MobilePayPaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Client/Version.php  3
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- tests/MobilePayPaymentTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-05-14 08:57 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +        $mobilePayPaymentObject = new MobilePayPaymentObject();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid excessively long variable names like $mobilePayPaymentObject. Keep variable name length under 20.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-05-14 08:57 UTC, payex-dev commented on src/SwedbankPay/Api/Client/Version.php
> +        if (file_exists($composerLockPath)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The use of function file_exists() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-05-14 08:57 UTC, payex-dev commented on src/SwedbankPay/Api/Client/Version.php
> +        if (!file_exists($composerLockPath)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The use of function file_exists() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-05-14 08:57 UTC, payex-dev commented on src/SwedbankPay/Api/Client/Version.php
> +        if (file_exists($composerPath)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The use of function file_exists() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-08-25 07:03 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- tests/MobilePayPaymentTest.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/MobilePayPaymentObject.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-08-25 07:03 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +        $mobilePayPaymentObject = new MobilePayPaymentObject();
Codacy found an issue: [Avoid excessively long variable names like $mobilePayPaymentObject. Keep variable name length under 20.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-08-25 07:47 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- tests/MobilePayPaymentTest.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-08-25 07:47 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +        $mobilePayPaymentObject = new PaymentObject();
Codacy found an issue: [Avoid excessively long variable names like $mobilePayPaymentObject. Keep variable name length under 20.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-08-25 09:02 UTC, asbjornu requested changes
The unit tests are failing, please fix them.

2020-08-29 17:48 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- tests/MobilePayPaymentTest.php  3
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-08-29 17:48 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +        $mobilePayPaymentObject = new PaymentObject();
Codacy found an issue: [Avoid excessively long variable names like $mobilePayPaymentObject. Keep variable name length under 20.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-08-29 17:48 UTC, payex-dev commented on tests/bootstrap.php
> +        define('PAYEE_ID_MOBILEPAY', getenv('PAYEE_ID_MOBILEPAY'));
Codacy found an issue: [The use of function getenv() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-08-29 17:48 UTC, payex-dev commented on tests/bootstrap.php
> +        define('MERCHANT_TOKEN_MOBILEPAY', getenv('MERCHANT_TOKEN_MOBILEPAY'));
Codacy found an issue: [The use of function getenv() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-08-29 17:48 UTC, payex-dev commented on tests/bootstrap.php
> +    if (getenv('MERCHANT_TOKEN_MOBILEPAY') && getenv('PAYEE_ID_MOBILEPAY')) {
Codacy found an issue: [The use of function getenv() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-04 17:37 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- tests/MobilePayPaymentTest.php  3
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-09-04 17:37 UTC, payex-dev commented on tests/bootstrap.php
> +        define('MERCHANT_TOKEN_MOBILEPAY', getenv('MERCHANT_TOKEN_MOBILEPAY'));
Codacy found an issue: [The use of function getenv() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-04 17:37 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +    public function testReversal($paymentId, $capture)
Codacy found an issue: [Avoid unused parameters such as '$paymentId'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-04 17:37 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +    public function testCapture($paymentId)
Codacy found an issue: [Avoid unused parameters such as '$paymentId'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-04 17:37 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +        $mobilePayPaymentObject = new PaymentObject();
Codacy found an issue: [Avoid excessively long variable names like $mobilePayPaymentObject. Keep variable name length under 20.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-04 17:37 UTC, payex-dev commented on tests/bootstrap.php
> +        define('PAYEE_ID_MOBILEPAY', getenv('PAYEE_ID_MOBILEPAY'));
Codacy found an issue: [The use of function getenv() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-04 17:37 UTC, payex-dev commented on tests/bootstrap.php
> +    if (getenv('MERCHANT_TOKEN_MOBILEPAY') && getenv('PAYEE_ID_MOBILEPAY')) {
Codacy found an issue: [The use of function getenv() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-04 17:37 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +class MobilePayPaymentTest extends TestCase
Codacy found an issue: [The class MobilePayPaymentTest has a coupling between objects value of 39. Consider to reduce the number of dependencies under 13.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-04 17:37 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +class MobilePayPaymentTest extends TestCase
Codacy found an issue: [The class MobilePayPaymentTest has 14 non-getter- and setter-methods. Consider refactoring MobilePayPaymentTest to keep number of methods under 10.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-04 18:53 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- tests/MobilePayPaymentTest.php  3
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-09-04 18:53 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +class MobilePayPaymentTest extends TestCase
Codacy found an issue: [The class MobilePayPaymentTest has 14 non-getter- and setter-methods. Consider refactoring MobilePayPaymentTest to keep number of methods under 10.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-04 18:53 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +class MobilePayPaymentTest extends TestCase
Codacy found an issue: [The class MobilePayPaymentTest has a coupling between objects value of 39. Consider to reduce the number of dependencies under 13.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-07 17:32 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- tests/MobilePayPaymentTest.php  3
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-09-07 17:32 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +class MobilePayPaymentTest extends TestCase
Codacy found an issue: [The class MobilePayPaymentTest has 14 non-getter- and setter-methods. Consider refactoring MobilePayPaymentTest to keep number of methods under 10.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-07 17:32 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +class MobilePayPaymentTest extends TestCase
Codacy found an issue: [The class MobilePayPaymentTest has a coupling between objects value of 39. Consider to reduce the number of dependencies under 13.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-08 08:39 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- tests/MobilePayPaymentTest.php  3
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-09-08 08:39 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +class MobilePayPaymentTest extends TestCase
Codacy found an issue: [The class MobilePayPaymentTest has 14 non-getter- and setter-methods. Consider refactoring MobilePayPaymentTest to keep number of methods under 10.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-08 08:39 UTC, payex-dev commented on tests/MobilePayPaymentTest.php
> +class MobilePayPaymentTest extends TestCase
Codacy found an issue: [The class MobilePayPaymentTest has a coupling between objects value of 39. Consider to reduce the number of dependencies under 13.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329)

2020-09-08 21:45 UTC, asbjornu commented
Please fix the tests

2020-09-11 05:56 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- tests/MobilePayPaymentTest.php  3
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-09-11 11:11 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/MobilePayPaymentTest.php  3
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-09-11 11:19 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/Vipps/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- tests/MobilePayPaymentTest.php  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-09-11 11:27 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- tests/MobilePayPaymentTest.php  3
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/Vipps/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-09-11 11:30 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/Vipps/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- tests/MobilePayPaymentTest.php  3
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-09-11 11:45 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransaction.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetTransactions.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCaptures.php  1
- src/SwedbankPay/Api/Service/Vipps/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentUrl.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/GetPayment.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentPayeeInfo.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorizations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellation.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/Item/AuthorizationListItem.php  1
- tests/MobilePayPaymentTest.php  3
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Resource/Collection/AuthorizationListCollection.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/Payment.php  2
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/CreateCapture.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetAuthorization.php  1
- src/SwedbankPay/Api/Service/MobilePay/Request/Purchase.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversal.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetReversals.php  1
- src/SwedbankPay/Api/Service/MobilePay/Transaction/Request/GetCancellations.php  1
- src/SwedbankPay/Api/Service/MobilePay/Resource/Request/PaymentObject.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5056329&bid=16644102)

2020-09-11 11:46 UTC, aait commented
> Please fix the tests

Done.

2020-09-11 22:10 UTC, asbjornu approved these changes

2020-09-14 10:03 UTC, merged